In [2]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path = kagglehub.dataset_download("osmi/mental-health-in-tech-2016")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\ugniu\.cache\kagglehub\datasets\osmi\mental-health-in-tech-2016\versions\2

In [3]:
#getting the  basic overview of the file

df = pd.read_csv( r"C:\Users\ugniu\PycharmProjects\Unsupervised  learning\Data\Raw\mental-heath-in-tech-2016_20161114.csv")


print(df.shape)
df.head()

(1433, 63)

,Are you self-employed?,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health concerns and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:",...,"If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?","If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?",What is your age?,What is your gender?,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,Which of the following best describes your work position?,Do you work remotely?
0,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,...,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
1,0,6-25,1.0,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
2,0,6-25,1.0,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,...,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
4,0,6-25,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,...,Sometimes,Sometimes,43,Female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes

In [4]:
#gathering info about the records and missing values and attributes (63 total)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1433 entries, 0 to 1432
Data columns (total 63 columns):
 #   Column                                                                                                                                                                            Non-Null Count  Dtype
---  ------                                                                                                                                                                            --------------  -----
 0   Are you self-employed?                                                                                                                                                            1433 non-null   int64
 1   How many employees does your company or organization have?                                                                                                                        1146 non-null   object
 2   Is your employer primarily a tech company/organization?                                                                                                                           1146 non-null   float64
 3   Is your primary role within your company related to tech/IT?                                                                                                                      263 non-null    float64
 4   Does your employer provide mental health benefits as part of healthcare coverage?                                                                                                 1146 non-null   object
 5   Do you know the options for mental health care available under your employer-provided coverage?                                                                                   1013 non-null   object
 6   Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?                                            1146 non-null   object
 7   Does your employer offer resources to learn more about mental health concerns and options for seeking help?                                                                       1146 non-null   object
 8   Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?                                    1146 non-null   object
 9   If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:                                                                       1146 non-null   object
 10  Do you think that discussing a mental health disorder with your employer would have negative consequences?                                                                        1146 non-null   object
 11  Do you think that discussing a physical health issue with your employer would have negative consequences?                                                                         1146 non-null   object
 12  Would you feel comfortable discussing a mental health disorder with your coworkers?                                                                                               1146 non-null   object
 13  Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?                                                                                    1146 non-null   object
 14  Do you feel that your employer takes mental health as seriously as physical health?                                                                                               1146 non-null   object
 15  Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?                                               1146 non-null   object
 16  Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?                                                             287 non-null    float64
 17  Do you know local or online resources to seek help for a mental health disorder?                                                                                                  287 non-null    object
 18  If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?                                                      287 non-null    object
 19  If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?                                                      144 non-null    object
 20  If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?                                                            287 non-null    object
 21  If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?                                                            287 non-null    object
 22  Do you believe your productivity is ever affected by a mental health issue?                                                                                                       287 non-null    object
 23  If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?                                              204 non-null    object
 24  Do you have previous employers?                                                                                                                                                   1433 non-null   int64
 25  Have your previous employers provided mental health benefits?                                                                                                                     1264 non-null   object
 26  Were you aware of the options for mental health care provided by your previous employers?                                                                                         1264 non-null   object
 27  Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?                                                 1264 non-null   object
 28  Did your previous employers provide resources to learn more about mental health issues and how to seek help?                                                                      1264 non-null   object
 29  Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?                                      1264 non-null   object
 30  Do you think that discussing a mental health disorder with previous employers would have negative consequences?                                                                   1264 non-null   object
 31  Do you think that discussing a physical health issue with previous employers would have negative consequences?                                                                    1264 non-null   object
 32  Would you have been willing to discuss a mental health issue with your previous co-workers?                                                                                       1264 non-null   object
 33  Would you have been willing to discuss a mental health issue with your direct supervisor(s)?                                                                                      1264 non-null   object
 34  Did you feel that your previous employers took mental health as seriously as physical health?                                                                                     1264 non-null   object
 35  Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?                                                            1264 non-null   object
 36  Would you be willing to bring up a physical health issue with a potential employer in an interview?                                                                               1433 non-null   object
 37  Why or why not?                                                                                                                                                                   1095 non-null   object
 38  Would you bring up a mental health issue with a potential employer in an interview?                                                                                               1433 non-null   object
 39  Why or why not?.1                                                                                                                                                                 1126 non-null   object
 40  Do you feel that being identified as a person with a mental health issue would hurt your career?                                                                                  1433 non-null   object
 41  Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?                                                    1433 non-null   object
 42  How willing would you be to share with friends and family that you have a mental illness?                                                                                         1433 non-null   object
 43  Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?                                        1344 non-null   object
 44  Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?  657 non-null    object
 45  Do you have a family history of mental illness?                                                                                                                                   1433 non-null   object
 46  Have you had a mental health disorder in the past?                                                                                                                                1433 non-null   object
 47  Do you currently have a mental health disorder?                                                                                                                                   1433 non-null   object
 48  If yes, what condition(s) have you been diagnosed with?                                                                                                                           568 non-null    object
 49  If maybe, what condition(s) do you believe you have?                                                                                                                              322 non-null    object
 50  Have you been diagnosed with a mental health condition by a medical professional?                                                                                                 1433 non-null   object
 51  If so, what condition(s) were you diagnosed with?                                                                                                                                 711 non-null    object
 52  Have you ever sought treatment for a mental health issue from a mental health professional?                                                                                       1433 non-null   int64
 53  If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?                                                                  1433 non-null   object
 54  If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?                                                              1433 non-null   object
 55  What is your age?                                                                                                                                                                 1433 non-null   int64
 56  What is your gender?                                                                                                                                                              1430 non-null   object
 57  What country do you live in?                                                                                                                                                      1433 non-null   object
 58  What US state or territory do you live in?                                                                                                                                        840 non-null    object
 59  What country do you work in?                                                                                                                                                      1433 non-null   object
 60  What US state or territory do you work in?                                                                                                                                        851 non-null    object
 61  Which of the following best describes your work position?                                                                                                                         1433 non-null   object
 62  Do you work remotely?                                                                                                                                                             1433 non-null   object
dtypes: float64(3), int64(4), object(56)
memory usage: 705.4+ KB

In [5]:
#checking the data types to see  what attributes will have to be converted
df.dtypes.value_counts()

object     56
int64       4
float64     3
Name: count, dtype: int64

In [6]:
df.describe()

,Are you self-employed?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Do you have medical coverage (private insurance or state-provided) which includes treatment of mental health issues?,Do you have previous employers?,Have you ever sought treatment for a mental health issue from a mental health professional?,What is your age?
count,1433.000000,1146.000000,263.000000,287.000000,1433.000000,1433.000000,1433.000000
mean,0.200279,0.770506,0.942966,0.644599,0.882066,0.585485,34.286113
std,0.400349,0.420691,0.232350,0.479471,0.322643,0.492810,11.290931
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
25%,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,28.000000
50%,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,33.000000
75%,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,39.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,323.000000

In [7]:
# unique values in a column
pd.set_option('display.max_rows', None)

# we want to identify columns have an open questions answers
df.nunique(dropna=False).sort_values()

Are you self-employed?                                                                                                                                                                 2
Do you have previous employers?                                                                                                                                                        2
Have you been diagnosed with a mental health condition by a medical professional?                                                                                                      2
Have you ever sought treatment for a mental health issue from a mental health professional?                                                                                            2
Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?                                                                  3
Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?                                                    3
Is your primary role within your company related to tech/IT?                                                                                                                           3
Is your employer primarily a tech company/organization?                                                                                                                                3
Have you had a mental health disorder in the past?                                                                                                                                     3
Do you currently have a mental health disorder?                                                                                                                                        3
Do you work remotely?                                                                                                                                                                  3
Do you have a family history of mental illness?                                                                                                                                        3
Would you be willing to bring up a physical health issue with a potential employer in an interview?                                                                                    3
Would you bring up a mental health issue with a potential employer in an interview?                                                                                                    3
Does your employer offer resources to learn more about mental health concerns and options for seeking help?                                                                            4
Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?                                                 4
Did your previous employers provide resources to learn more about mental health issues and how to seek help?                                                                           4
Do you think that discussing a physical health issue with previous employers would have negative consequences?                                                                         4
Do you know local or online resources to seek help for a mental health disorder?                                                                                                       4
Do you think that discussing a mental health disorder with your employer would have negative consequences?                                                                             4
Do you feel that your employer takes mental health as seriously as physical health?                                                                                                    4
Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?                                                                 4
Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?       4
Would you have been willing to discuss a mental health issue with your previous co-workers?                                                                                            4
Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?                                                                                         4
Would you feel comfortable discussing a mental health disorder with your coworkers?                                                                                                    4
Do you think that discussing a physical health issue with your employer would have negative consequences?                                                                              4
Do you know the options for mental health care available under your employer-provided coverage?                                                                                        4
Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?                                         4
If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?                                                           4
Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?                                                      5
Does your employer provide mental health benefits as part of healthcare coverage?                                                                                                      5
If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?                                                                   5
If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?                                                                       5
Were you aware of the options for mental health care provided by your previous employers?                                                                                              5
Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?                                                         5
Have your previous employers provided mental health benefits?                                                                                                                          5
Do you believe your productivity is ever affected by a mental health issue?                                                                                                            5
Do you think that discussing a mental health disorder with previous employers would have negative consequences?                                                                        5
Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?                                           5
If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?                                                                 5
If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?                                                   5
Would you have been willing to discuss a mental health issue with your direct supervisor(s)?                                                                                           5
Did you feel that your previous employers took mental health as seriously as physical health?                                                                                          5
Do you feel that being identified as a person with a mental health issue would hurt your career?                                                                                       5
Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?                                             5
If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?                                                           6
If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?                                                                 6
How willing would you be to share with friends and family that you have a mental illness?                                                                                              6
If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:                                                                            7
How many employees does your company or organization have?                                                                                                                             7
What US state or territory do you live in?                                                                                                                                            48
What US state or territory do you work in?                                                                                                                                            49
What country do you live in?                                                                                                                                                          53
What country do you work in?                                                                                                                                                          53
What is your age?                                                                                                                                                                     53
What is your gender?                                                                                                                                                                  71
If maybe, what condition(s) do you believe you have?                                                                                                                                 100
If so, what condition(s) were you diagnosed with?                                                                                                                                    117
If yes, what condition(s) have you been diagnosed with?                                                                                                                              129
Which of the following best describes your work position?                                                                                                                            264
Why or why not?.1                                                                                                                                                                   1081
Why or why not?                                                                                                                                                                     1086
dtype: int64

In [8]:
for column in df.columns:
    print("\n" + "=" * 80)
    print(df[column].value_counts(dropna=False))

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

Which of the following best describes your work position?
Back-end Developer                                                                                                                            263
Front-end Developer                                                                                                                           125
Other                                                                                                                                         112
Supervisor/Team Lead                                                                                                                           68
Back-end Developer|Front-end Developer                                                                                                         61
DevOps/SysAdmin                                                                                                                                54
One-person shop                                                                                                                                50
Executive Leadership                                                                                                                           46
Front-end Developer|Back-end Developer                                                                                                         40
Support                                                                                                                                        34
Dev Evangelist/Advocate                                                                                                                        28
Designer                                                                                                                                       28
Supervisor/Team Lead|Back-end Developer                                                                                                        19
Front-end Developer|Designer                                                                                                                   18
DevOps/SysAdmin|Back-end Developer|Front-end Developer                                                                                         17
Back-end Developer|DevOps/SysAdmin                                                                                                             16
DevOps/SysAdmin|Back-end Developer                                                                                                             15
Supervisor/Team Lead|Back-end Developer|Front-end Developer                                                                                    15
Front-end Developer|Back-end Developer|DevOps/SysAdmin                                                                                         12
Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer                                                                                         9
DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer                                                                                  8
Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Front-end Developer                                                                     8
Back-end Developer|One-person shop                                                                                                              7
DevOps/SysAdmin|Support                                                                                                                         6
Supervisor/Team Lead|Front-end Developer                                                                                                        6
Front-end Developer|Back-end Developer|Supervisor/Team Lead                                                                                     6
Support|Back-end Developer                                                                                                                      6
Front-end Developer|Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead                                                                     6
HR                                                                                                                                              5
DevOps/SysAdmin|Back-end Developer|Front-end Developer|Designer                                                                                 5
One-person shop|Back-end Developer                                                                                                              5
Other|Back-end Developer                                                                                                                        5
One-person shop|Front-end Developer|Back-end Developer                                                                                          5
DevOps/SysAdmin|Supervisor/Team Lead                                                                                                            4
Back-end Developer|Front-end Developer|Designer                                                                                                 4
Support|Back-end Developer|Front-end Developer                                                                                                  4
Designer|Front-end Developer                                                                                                                    4
Dev Evangelist/Advocate|Back-end Developer                                                                                                      4
One-person shop|Back-end Developer|DevOps/SysAdmin                                                                                              4
Executive Leadership|Supervisor/Team Lead                                                                                                       4
Supervisor/Team Lead|DevOps/SysAdmin                                                                                                            4
Sales                                                                                                                                           4
Back-end Developer|Supervisor/Team Lead                                                                                                         4
Other|Dev Evangelist/Advocate                                                                                                                   3
Back-end Developer|Front-end Developer|One-person shop                                                                                          3
DevOps/SysAdmin|Front-end Developer|Back-end Developer|Support                                                                                  3
Support|Back-end Developer|Front-end Developer|One-person shop                                                                                  3
Support|Other                                                                                                                                   3
Supervisor/Team Lead|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|Designer                                                    3
Dev Evangelist/Advocate|Back-end Developer|Front-end Developer                                                                                  3
DevOps/SysAdmin|Back-end Developer|Front-end Developer|One-person shop                                                                          3
One-person shop|Front-end Developer|Back-end Developer|DevOps/SysAdmin                                                                          3
One-person shop|Designer|Front-end Developer                                                                                                    3
Other|Supervisor/Team Lead                                                                                                                      3
Dev Evangelist/Advocate|DevOps/SysAdmin|Back-end Developer                                                                                      3
DevOps/SysAdmin|Support|Back-end Developer                                                                                                      3
Supervisor/Team Lead|Support                                                                                                                    3
Front-end Developer|Back-end Developer|Support                                                                                                  3
Front-end Developer|Back-end Developer|Executive Leadership                                                                                     2
Other|Front-end Developer|Designer|One-person shop                                                                                              2
Other|Back-end Developer|Front-end Developer|Designer                                                                                           2
Other|DevOps/SysAdmin|Back-end Developer                                                                                                        2
Support|Front-end Developer|Back-end Developer                                                                                                  2
Back-end Developer|DevOps/SysAdmin|Dev Evangelist/Advocate|Supervisor/Team Lead                                                                 2
Supervisor/Team Lead|Back-end Developer|One-person shop                                                                                         2
Designer|Front-end Developer|Back-end Developer|Supervisor/Team Lead                                                                            2
Front-end Developer|Back-end Developer|Dev Evangelist/Advocate                                                                                  2
Supervisor/Team Lead|Back-end Developer|Front-end Developer|Designer                                                                            2
Front-end Developer|One-person shop                                                                                                             2
One-person shop|Other                                                                                                                           2
One-person shop|Designer                                                                                                                        2
Supervisor/Team Lead|DevOps/SysAdmin|Front-end Developer|Back-end Developer                                                                     2
One-person shop|Front-end Developer|Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead                                                     2
Support|DevOps/SysAdmin                                                                                                                         2
Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead                                                                                         2
Other|Dev Evangelist/Advocate|Support                                                                                                           2
Supervisor/Team Lead|Back-end Developer|DevOps/SysAdmin                                                                                         2
Back-end Developer|Dev Evangelist/Advocate                                                                                                      2
Supervisor/Team Lead|Executive Leadership                                                                                                       2
One-person shop|Front-end Developer                                                                                                             2
Supervisor/Team Lead|Front-end Developer|Back-end Developer                                                                                     2
Supervisor/Team Lead|Front-end Developer|Back-end Developer|DevOps/SysAdmin                                                                     2
Back-end Developer|Dev Evangelist/Advocate|Supervisor/Team Lead                                                                                 2
DevOps/SysAdmin|One-person shop                                                                                                                 2
Dev Evangelist/Advocate|DevOps/SysAdmin                                                                                                         2
Front-end Developer|Supervisor/Team Lead                                                                                                        2
Other|Supervisor/Team Lead|Back-end Developer|Front-end Developer                                                                               2
Supervisor/Team Lead|DevOps/SysAdmin|Support                                                                                                    2
Other|Support                                                                                                                                   2
DevOps/SysAdmin|Dev Evangelist/Advocate|Supervisor/Team Lead|Executive Leadership                                                               2
Supervisor/Team Lead|Support|Back-end Developer                                                                                                 2
Support|Back-end Developer|One-person shop                                                                                                      2
DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|Designer                                                                         1
Supervisor/Team Lead|Front-end Developer|Designer                                                                                               1
Dev Evangelist/Advocate|DevOps/SysAdmin|Designer|Front-end Developer|Back-end Developer                                                         1
Support|Sales|Back-end Developer|Front-end Developer|Designer|One-person shop                                                                   1
DevOps/SysAdmin|Support|Back-end Developer|One-person shop|Front-end Developer                                                                  1
One-person shop|Designer|Sales|Support|Supervisor/Team Lead                                                                                     1
Other|One-person shop|Designer|Front-end Developer                                                                                              1
Supervisor/Team Lead|Designer                                                                                                                   1
Back-end Developer|Support|Supervisor/Team Lead                                                                                                 1
Other|Supervisor/Team Lead|DevOps/SysAdmin|Support|Front-end Developer|Back-end Developer                                                       1
Supervisor/Team Lead|Support|Back-end Developer|Front-end Developer                                                                             1
Other|One-person shop|Designer|Front-end Developer|Back-end Developer|Support|Supervisor/Team Lead                                              1
Other|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|One-person shop               1
Support|Back-end Developer|Front-end Developer|Designer                                                                                         1
One-person shop|Designer|Sales|Executive Leadership                                                                                             1
Executive Leadership|Supervisor/Team Lead|Dev Evangelist/Advocate|Back-end Developer                                                            1
Executive Leadership|Front-end Developer|Back-end Developer|Sales|Supervisor/Team Lead                                                          1
Supervisor/Team Lead|DevOps/SysAdmin|Support|Back-end Developer                                                                                 1
One-person shop|Front-end Developer|Back-end Developer|Dev Evangelist/Advocate|Other                                                            1
Other|Supervisor/Team Lead|Support|Back-end Developer|Designer                                                                                  1
Other|Executive Leadership                                                                                                                      1
One-person shop|Back-end Developer|Supervisor/Team Lead                                                                                         1
One-person shop|Back-end Developer|Sales|DevOps/SysAdmin|Executive Leadership                                                                   1
Dev Evangelist/Advocate|Support|Back-end Developer                                                                                              1
One-person shop|Designer|Front-end Developer|Back-end Developer|Support|Dev Evangelist/Advocate                                                 1
Other|Front-end Developer|Back-end Developer|Sales|DevOps/SysAdmin|Dev Evangelist/Advocate                                                      1
HR|Supervisor/Team Lead|Executive Leadership                                                                                                    1
Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Designer                                                                                1
Other|Dev Evangelist/Advocate|Sales|Back-end Developer|Front-end Developer                                                                      1
Dev Evangelist/Advocate|Back-end Developer|Designer|Front-end Developer                                                                         1
One-person shop|Front-end Developer|Back-end Developer|Supervisor/Team Lead|Executive Leadership                                                1
Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Designer|Front-end Developer                                                            1
One-person shop|Back-end Developer|DevOps/SysAdmin|Dev Evangelist/Advocate|Other                                                                1
Supervisor/Team Lead|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer                                                             1
DevOps/SysAdmin|Front-end Developer|Back-end Developer                                                                                          1
Other|Executive Leadership|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Back-end Developer|One-person shop                      1
One-person shop|Back-end Developer|Other                                                                                                        1
HR|Dev Evangelist/Advocate|Sales                                                                                                                1
One-person shop|DevOps/SysAdmin|Executive Leadership                                                                                            1
DevOps/SysAdmin|Back-end Developer|One-person shop|Front-end Developer                                                                          1
Support|HR|Supervisor/Team Lead|Executive Leadership                                                                                            1
Executive Leadership|Dev Evangelist/Advocate                                                                                                    1
DevOps/SysAdmin|Executive Leadership                                                                                                            1
DevOps/SysAdmin|One-person shop|Front-end Developer|Back-end Developer                                                                          1

In [9]:

for column in df.columns:
    print("\n" + "=" * 80)
    # show only 10 values
    print(df[column].value_counts(dropna=False).head(10))
    print(f"n_unique: {df[column].nunique()}")

================================================================================
Are you self-employed?
0    1146
1     287
Name: count, dtype: int64
n_unique: 2

================================================================================
How many employees does your company or organization have?
26-100            292
NaN               287
More than 1000    256
100-500           248
6-25              210
500-1000           80
1-5                60
Name: count, dtype: int64
n_unique: 6

================================================================================
Is your employer primarily a tech company/organization?
1.0    883
NaN    287
0.0    263
Name: count, dtype: int64
n_unique: 2

================================================================================
Is your primary role within your company related to tech/IT?
NaN    1170
1.0     248
0.0      15
Name: count, dtype: int64
n_unique: 2

================================================================================
Does your employer provide mental health benefits as part of healthcare coverage?
Yes                                531
I don't know                       319
NaN                                287
No                                 213
Not eligible for coverage / N/A     83
Name: count, dtype: int64
n_unique: 4

================================================================================
Do you know the options for mental health care available under your employer-provided coverage?
NaN              420
No               354
I am not sure    352
Yes              307
Name: count, dtype: int64
n_unique: 3

================================================================================
Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?
No              813
NaN             287
Yes             230
I don't know    103
Name: count, dtype: int64
n_unique: 3

================================================================================
Does your employer offer resources to learn more about mental health concerns and options for seeking help?
No              531
I don't know    320
Yes             295
NaN             287
Name: count, dtype: int64
n_unique: 3

================================================================================
Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?
I don't know    742
Yes             320
NaN             287
No               84
Name: count, dtype: int64
n_unique: 3

================================================================================
If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:
NaN                           287
Somewhat easy                 281
Very easy                     220
Somewhat difficult            199
Neither easy nor difficult    178
I don't know                  150
Very difficult                118
Name: count, dtype: int64
n_unique: 6

================================================================================
Do you think that discussing a mental health disorder with your employer would have negative consequences?
Maybe    487
No       438
NaN      287
Yes      221
Name: count, dtype: int64
n_unique: 3

================================================================================
Do you think that discussing a physical health issue with your employer would have negative consequences?
No       837
NaN      287
Maybe    268
Yes       41
Name: count, dtype: int64
n_unique: 3

================================================================================
Would you feel comfortable discussing a mental health disorder with your coworkers?
Maybe    479
No       392
NaN      287
Yes      275
Name: count, dtype: int64
n_unique: 3

================================================================================
Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?
Yes      428
Maybe    382
No       336
NaN      287
Name: count, dtype: int64
n_unique: 3

================================================================================
Do you feel that your employer takes mental health as seriously as physical health?
I don't know    493
Yes             350
No              303
NaN             287
Name: count, dtype: int64
n_unique: 3

================================================================================
Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?
No     1048
NaN     287
Yes      98
Name: count, dtype: int64
n_unique: 2

================================================================================
Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?
NaN    1146
1.0     185
0.0     102
Name: count, dtype: int64
n_unique: 2

================================================================================
Do you know local or online resources to seek help for a mental health disorder?
NaN                     1146
I know some              141
Yes, I know several       83
No, I don't know any      63
Name: count, dtype: int64
n_unique: 3

================================================================================
If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?
NaN                                          1146
Not applicable to me                          101
No, because it would impact me negatively      83
Sometimes, if it comes up                      57
No, because it doesn't matter                  44
Yes, always                                     2
Name: count, dtype: int64
n_unique: 5

================================================================================
If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?
NaN             1289
I'm not sure      66
No                42
Yes               36
Name: count, dtype: int64
n_unique: 3

================================================================================
If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?
NaN                                          1146
Not applicable to me                          111
Sometimes, if it comes up                      99
No, because it would impact me negatively      51
No, because it doesn't matter                  15
Yes, always                                    11
Name: count, dtype: int64
n_unique: 5

================================================================================
If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?
NaN                     1146
Not applicable to me     133
I'm not sure              62
No                        57
Yes                       35
Name: count, dtype: int64
n_unique: 4

================================================================================
Do you believe your productivity is ever affected by a mental health issue?
NaN                     1146
Yes                      204
Unsure                    38
Not applicable to me      31
No                        14
Name: count, dtype: int64
n_unique: 4

================================================================================
If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?
NaN        1229
1-25%        92
26-50%       72
51-75%       26
76-100%      14
Name: count, dtype: int64
n_unique: 4

================================================================================
Do you have previous employers?
1    1264
0     169
Name: count, dtype: int64
n_unique: 2

================================================================================
Have your previous employers provided mental health benefits?
Some did             391
No, none did         372
I don't know         313
Yes, they all did    188
NaN                  169
Name: count, dtype: int64
n_unique: 4

================================================================================
Were you aware of the options for mental health care provided by your previous employers?
N/A (not currently aware)          582
I was aware of some                384
Yes, I was aware of all of them    181
NaN                                169
No, I only became aware later      117
Name: count, dtype: int64
n_unique: 4

================================================================================
Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?
None did             890
Some did             255
NaN                  169
I don't know          86
Yes, they all did     33
Name: count, dtype: int64
n_unique: 4

================================================================================
Did your previous employers provide resources to learn more about mental health issues and how to seek help?
None did             842
Some did             371
NaN                  169
Yes, they all did     51
Name: count, dtype: int64
n_unique: 3

================================================================================
Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?
I don't know    860
NaN             169
Yes, always     164
No              121
Sometimes       119
Name: count, dtype: int64
n_unique: 4

================================================================================
Do you think that discussing a mental health disorder with previous employers would have negative consequences?
Some of them        615
I don't know        310
Yes, all of them    226
NaN                 169
None of them        113
Name: count, dtype: int64
n_unique: 4

================================================================================
Do you think that discussing a physical health issue with previous employers would have negative consequences?
Some of them        631
None of them        559
NaN                 169
Yes, all of them     74
Name: count, dtype: int64
n_unique: 3

================================================================================
Would you have been willing to discuss a mental health issue with your previous co-workers?
Some of my previous employers           740
No, at none of my previous employers    430
NaN                                     169
Yes, at all of my previous employers     94
Name: count, dtype: int64
n_unique: 3

================================================================================
Would you have been willing to discuss a mental health issue with your direct supervisor(s)?
Some of my previous employers           654
No, at none of my previous employers    416
NaN                                     169
I don't know                            101
Yes, at all of my previous employers     93
Name: count, dtype: int64
n_unique: 4

================================================================================
Did you feel that your previous employers took mental health as seriously as physical health?
None did             463
Some did             427
I don't know         331
NaN                  169
Yes, they all did     43
Name: count, dtype: int64
n_unique: 4

================================================================================
Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?
None of them        758
Some of them        444
NaN                 169
Yes, all of them     62
Name: count, dtype: int64
n_unique: 3

================================================================================
Would you be willing to bring up a physical health issue with a potential employer in an interview?
Maybe    633
No       441
Yes      359
Name: count, dtype: int64
n_unique: 3

================================================================================
Why or why not?
NaN                                                                                                                                                                                                                                                                                                   338
I don't know                                                                                                                                                                                                                                                                                            3
Fear of discrimination                                                                                                                                                                                                                                                                                  3
Not relevant                                                                                                                                                                                                                                                                                            3
bias                                                                                                                                                                                                                                                                                                    2
None of their business.                                                                                                                                                                                                                                                                                 2
Fear of not getting the job                                                                                                                                                                                                                                                                             2
honesty                                                                                                                                                                                                                                                                                                 2
It would depend on the health issue. If there is a health issue that would not immediately affect my job performance, such as diabetes, I would not bring it up during the interview. If it was something more severe, such as narcolepsy, I might bring it up depending on how controlled it was.      1
They would provable need to know, to Judge if I can do my job or not.                                                                                                                                                                                                                                   1
Name: count, dtype: int64
n_unique: 1085

================================================================================
Would you bring up a mental health issue with a potential employer in an interview?
No       883
Maybe    438
Yes      112
Name: count, dtype: int64
n_unique: 3

================================================================================
Why or why not?.1
NaN                            307
Stigma                          14
Stigma.                          9
Same as above                    7
See above                        4
stigma                           3
Fear of not getting the job      3
same as above                    3
Same as above.                   3
Same reason as above.            3
Name: count, dtype: int64
n_unique: 1080

================================================================================
Do you feel that being identified as a person with a mental health issue would hurt your career?
Maybe                         588
Yes, I think it would         563
No, I don't think it would    147
Yes, it has                   105
No, it has not                 30
Name: count, dtype: int64
n_unique: 5

================================================================================
Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?
Maybe                           591
Yes, I think they would         403
No, I don't think they would    348
No, they do not                  49
Yes, they do                     42
Name: count, dtype: int64
n_unique: 5

================================================================================
How willing would you be to share with friends and family that you have a mental illness?
Somewhat open                                            640
Very open                                                251
Somewhat not open                                        214
Neutral                                                  141
Not applicable to me (I do not have a mental illness)    112
Not open at all                                           75
Name: count, dtype: int64
n_unique: 6

================================================================================
Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?
No                    567
Maybe/Not sure        346
Yes, I observed       264
Yes, I experienced    167
NaN                    89
Name: count, dtype: int64
n_unique: 4

================================================================================
Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?
NaN      776
Yes      246
No       234
Maybe    177
Name: count, dtype: int64
n_unique: 3

================================================================================
Do you have a family history of mental illness?
Yes             670
No              488
I don't know    275
Name: count, dtype: int64
n_unique: 3

================================================================================
Have you had a mental health disorder in the past?
Yes      736
No       451
Maybe    246
Name: count, dtype: int64
n_unique: 3

================================================================================
Do you currently have a mental health disorder?
Yes      575
No       531
Maybe    327
Name: count, dtype: int64
n_unique: 3

================================================================================
If yes, what condition(s) have you been diagnosed with?
NaN                                                                                                                                               865
Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)                                             117
Mood Disorder (Depression, Bipolar Disorder, etc)                                                                                                 102
Anxiety Disorder (Generalized, Social, Phobia, etc)                                                                                                47
Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder     26
Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder                                                         22
Attention Deficit Hyperactivity Disorder                                                                                                           18

In [10]:
#checking the percentage of missing values/total

# 15 columns have a missing rate of 40 % or higher, need investigation
(df.isna().mean() * 100).sort_values(ascending=False)

If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?                                                        89.951151
If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?                                                85.764131
Is your primary role within your company related to tech/IT?                                                                                                                        81.646895
Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?                                                               79.972087
If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?                                                        79.972087
If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?                                                              79.972087
If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?                                                              79.972087
Do you know local or online resources to seek help for a mental health disorder?                                                                                                    79.972087
Do you believe your productivity is ever affected by a mental health issue?                                                                                                         79.972087
If maybe, what condition(s) do you believe you have?                                                                                                                                77.529658
If yes, what condition(s) have you been diagnosed with?                                                                                                                             60.362875
Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?    54.152128
If so, what condition(s) were you diagnosed with?                                                                                                                                   50.383810
What US state or territory do you live in?                                                                                                                                          41.381717
What US state or territory do you work in?                                                                                                                                          40.614096
Do you know the options for mental health care available under your employer-provided coverage?                                                                                     29.309142
Why or why not?                                                                                                                                                                     23.586881
Why or why not?.1                                                                                                                                                                   21.423587
Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?                                                                                      20.027913
Do you think that discussing a mental health disorder with your employer would have negative consequences?                                                                          20.027913
If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:                                                                         20.027913
Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?                                      20.027913
Do you think that discussing a physical health issue with your employer would have negative consequences?                                                                           20.027913
Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?                                                 20.027913
Do you feel that your employer takes mental health as seriously as physical health?                                                                                                 20.027913
Would you feel comfortable discussing a mental health disorder with your coworkers?                                                                                                 20.027913
How many employees does your company or organization have?                                                                                                                          20.027913
Does your employer provide mental health benefits as part of healthcare coverage?                                                                                                   20.027913
Is your employer primarily a tech company/organization?                                                                                                                             20.027913
Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?                                              20.027913
Does your employer offer resources to learn more about mental health concerns and options for seeking help?                                                                         20.027913
Did you feel that your previous employers took mental health as seriously as physical health?                                                                                       11.793440
Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?                                                              11.793440
Did your previous employers provide resources to learn more about mental health issues and how to seek help?                                                                        11.793440
Do you think that discussing a mental health disorder with previous employers would have negative consequences?                                                                     11.793440
Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?                                                   11.793440
Were you aware of the options for mental health care provided by your previous employers?                                                                                           11.793440
Have your previous employers provided mental health benefits?                                                                                                                       11.793440
Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?                                        11.793440
Would you have been willing to discuss a mental health issue with your previous co-workers?                                                                                         11.793440
Do you think that discussing a physical health issue with previous employers would have negative consequences?                                                                      11.793440
Would you have been willing to discuss a mental health issue with your direct supervisor(s)?                                                                                        11.793440
Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?                                           6.210747
What is your gender?                                                                                                                                                                 0.209351
Are you self-employed?                                                                                                                                                               0.000000
Do you have previous employers?                                                                                                                                                      0.000000
Would you be willing to bring up a physical health issue with a potential employer in an interview?                                                                                  0.000000
Have you had a mental health disorder in the past?                                                                                                                                   0.000000
Do you have a family history of mental illness?                                                                                                                                      0.000000
Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?                                                       0.000000
How willing would you be to share with friends and family that you have a mental illness?                                                                                            0.000000
Do you feel that being identified as a person with a mental health issue would hurt your career?                                                                                     0.000000
Would you bring up a mental health issue with a potential employer in an interview?                                                                                                  0.000000
Have you been diagnosed with a mental health condition by a medical professional?                                                                                                    0.000000
Do you currently have a mental health disorder?                                                                                                                                      0.000000
If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?                                                                 0.000000
If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?                                                                     0.000000
Have you ever sought treatment for a mental health issue from a mental health professional?                                                                                          0.000000
What is your age?                                                                                                                                                                    0.000000
What country do you live in?                                                                                                                                                         0.000000
What country do you work in?                                                                                                                                                         0.000000
Which of the following best describes your work position?                                                                                                                            0.000000
Do you work remotely?                                                                                                                                                                0.000000
dtype: float64

In [11]:
#row 57
df["What is your gender?"].unique()
#jesus

array(['Male', 'male', 'Male ', 'Female', 'M', 'female', 'm',
       'I identify as female.', 'female ', 'Bigender', 'non-binary',
       'Female assigned at birth ', 'F', 'Woman', 'man', 'fm', 'f',
       'Cis female ', 'Transitioned, M2F', 'Genderfluid (born female)',
       'Other/Transfeminine', 'Female or Multi-Gender Femme', 'Female ',
       'woman', 'female/woman', 'Cis male', 'Male.', 'Androgynous',
       'male 9:1 female, roughly', nan, 'Male (cis)', 'Other',
       'nb masculine', 'Cisgender Female', 'Man', 'Sex is male',
       'none of your business', 'genderqueer', 'cis male', 'Human',
       'Genderfluid', 'Enby', 'Malr', 'genderqueer woman', 'mtf', 'Queer',
       'Agender', 'Dude', 'Fluid',
       "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? ",
       'mail', 'M|', 'Male/genderqueer', 'fem', 'Nonbinary', 'male ',
       'human', 'Female (props for making this a freeform field, though)',
       ' Female', 'Unicorn', 'Cis Male', 'Male (trans, FtM)', 'Cis-woman',
       'Genderqueer', 'cisdude', 'Genderflux demi-girl',
       'female-bodied; no feelings about gender', 'cis man', 'AFAB',
       'Transgender woman', 'MALE'], dtype=object)

In [12]:
pd.crosstab(
    df["Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?"],
    df["Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?"].isna(),
    dropna=False,
)

Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?,False,True
Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?,,
Maybe/Not sure,272,74
No,0,567
"Yes, I experienced",139,28
"Yes, I observed",246,18
NaN,0,89

In [13]:
df["Which of the following best describes your work position?"].unique()

array(['Back-end Developer', 'Back-end Developer|Front-end Developer',
       'Supervisor/Team Lead',
       'Executive Leadership|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer',
       'DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|Designer',
       'Dev Evangelist/Advocate|Back-end Developer',
       'Support|Back-end Developer|One-person shop',
       'One-person shop|Front-end Developer|Back-end Developer',
       'Front-end Developer', 'Executive Leadership',
       'Supervisor/Team Lead|Dev Evangelist/Advocate|Back-end Developer|Front-end Developer',
       'DevOps/SysAdmin|Back-end Developer|Front-end Developer',
       'Designer', 'Other|Executive Leadership', 'One-person shop',
       'Other', 'Supervisor/Team Lead|Support|Back-end Developer',
       'Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer',
       'Other|Supervisor/Team Lead|Support|Back-end Developer|Designer',
       'Supervisor/Team Lead|Back-end Developer',
       'One-person shop|Front-end Developer|Back-end Developer|Dev Evangelist/Advocate|Other',
       'Supervisor/Team Lead|DevOps/SysAdmin|Support|Back-end Developer',
       'Executive Leadership|Front-end Developer|Back-end Developer|Sales|Supervisor/Team Lead',
       'Support|Other',
       'One-person shop|Back-end Developer|DevOps/SysAdmin',
       'Supervisor/Team Lead|Other', 'DevOps/SysAdmin|Back-end Developer',
       'Supervisor/Team Lead|Back-end Developer|Front-end Developer',
       'Front-end Developer|Back-end Developer|Executive Leadership',
       'Supervisor/Team Lead|Back-end Developer|Front-end Developer|One-person shop',
       'Supervisor/Team Lead|DevOps/SysAdmin', 'DevOps/SysAdmin',
       'Front-end Developer|Back-end Developer',
       'Supervisor/Team Lead|Back-end Developer|One-person shop',
       'Support',
       'Executive Leadership|Supervisor/Team Lead|Back-end Developer',
       'Front-end Developer|Back-end Developer|DevOps/SysAdmin',
       'Supervisor/Team Lead|Dev Evangelist/Advocate|Back-end Developer',
       'Back-end Developer|DevOps/SysAdmin',
       'One-person shop|Back-end Developer',
       'Back-end Developer|Supervisor/Team Lead',
       'Front-end Developer|Back-end Developer|Sales|Executive Leadership',
       'One-person shop|Back-end Developer|Sales|Support|DevOps/SysAdmin|Dev Evangelist/Advocate|Supervisor/Team Lead|Executive Leadership|Other',
       'Back-end Developer|DevOps/SysAdmin|Dev Evangelist/Advocate|Supervisor/Team Lead',
       'Front-end Developer|Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead',
       'Executive Leadership|Supervisor/Team Lead',
       'Supervisor/Team Lead|Back-end Developer|DevOps/SysAdmin|Dev Evangelist/Advocate',
       'One-person shop|Designer|Front-end Developer|Support',
       'One-person shop|Front-end Developer|Back-end Developer|DevOps/SysAdmin',
       'Other|Executive Leadership|Supervisor/Team Lead|Back-end Developer',
       'Executive Leadership|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Back-end Developer|Front-end Developer',
       'Supervisor/Team Lead|Front-end Developer',
       'Other|Back-end Developer|Front-end Developer|Designer',
       'Executive Leadership|DevOps/SysAdmin|Back-end Developer',
       'Other|Supervisor/Team Lead|Back-end Developer|One-person shop',
       'Dev Evangelist/Advocate|Support',
       'Supervisor/Team Lead|Front-end Developer|Back-end Developer|DevOps/SysAdmin',
       'HR', 'Dev Evangelist/Advocate',
       'Dev Evangelist/Advocate|Back-end Developer|Support',
       'Executive Leadership|DevOps/SysAdmin|Back-end Developer|Support',
       'DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer',
       'Dev Evangelist/Advocate|Back-end Developer|Front-end Developer',
       'Other|HR', 'Support|Back-end Developer',
       'DevOps/SysAdmin|Support',
       'Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead',
       'Designer|Front-end Developer|Back-end Developer',
       'Supervisor/Team Lead|Back-end Developer|Front-end Developer|Designer',
       'Other|Back-end Developer|Front-end Developer',
       'Front-end Developer|Back-end Developer|Sales|DevOps/SysAdmin',
       'Front-end Developer|Back-end Developer|Support',
       'One-person shop|Back-end Developer|Supervisor/Team Lead',
       'Front-end Developer|Designer', 'Other|Support',
       'DevOps/SysAdmin|One-person shop|Front-end Developer|Back-end Developer',
       'DevOps/SysAdmin|Executive Leadership',
       'Executive Leadership|Dev Evangelist/Advocate',
       'Back-end Developer|Dev Evangelist/Advocate',
       'Support|HR|Supervisor/Team Lead|Executive Leadership',
       'Supervisor/Team Lead|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|Designer',
       'Supervisor/Team Lead|Back-end Developer|DevOps/SysAdmin',
       'Back-end Developer|Front-end Developer|One-person shop',
       'Front-end Developer|Back-end Developer|Supervisor/Team Lead',
       'DevOps/SysAdmin|Front-end Developer|Back-end Developer|Support',
       'DevOps/SysAdmin|Back-end Developer|One-person shop|Front-end Developer',
       'One-person shop|DevOps/SysAdmin|Executive Leadership', 'Sales',
       'Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Front-end Developer',
       'Front-end Developer|Supervisor/Team Lead',
       'Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Designer|Front-end Developer',
       'Dev Evangelist/Advocate|DevOps/SysAdmin',
       'Support|Back-end Developer|Front-end Developer',
       'One-person shop|Front-end Developer|Back-end Developer|Supervisor/Team Lead|Executive Leadership',
       'Dev Evangelist/Advocate|Back-end Developer|Designer|Front-end Developer',
       'Other|Dev Evangelist/Advocate|Sales|Back-end Developer|Front-end Developer',
       'DevOps/SysAdmin|Dev Evangelist/Advocate|Supervisor/Team Lead|Executive Leadership',
       'Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Designer',
       'HR|Supervisor/Team Lead|Executive Leadership',
       'Other|Front-end Developer|Back-end Developer|Sales|DevOps/SysAdmin|Dev Evangelist/Advocate',
       'DevOps/SysAdmin|Supervisor/Team Lead',
       'One-person shop|Designer|Front-end Developer|Back-end Developer|Support|Dev Evangelist/Advocate',
       'Dev Evangelist/Advocate|Support|Back-end Developer',
       'One-person shop|Back-end Developer|Sales|DevOps/SysAdmin|Executive Leadership',
       'Front-end Developer|Back-end Developer|Support|DevOps/SysAdmin',
       'Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead|Other',
       'Supervisor/Team Lead|Support', 'HR|Dev Evangelist/Advocate|Sales',
       'Back-end Developer|Dev Evangelist/Advocate|Supervisor/Team Lead',
       'DevOps/SysAdmin|One-person shop',
       'Supervisor/Team Lead|Front-end Developer|Back-end Developer',
       'Back-end Developer|Front-end Developer|Designer',
       'One-person shop|Back-end Developer|Other',
       'Supervisor/Team Lead|DevOps/SysAdmin|Support',
       'Other|Executive Leadership|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Back-end Developer|One-person shop',
       'DevOps/SysAdmin|Front-end Developer|Back-end Developer',
       'Supervisor/Team Lead|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer',
       'DevOps/SysAdmin|Back-end Developer|Front-end Developer|Designer',
       'One-person shop|Back-end Developer|DevOps/SysAdmin|Dev Evangelist/Advocate|Other',
       'Other|Supervisor/Team Lead|Back-end Developer|Front-end Developer',
       'Other|Dev Evangelist/Advocate|One-person shop',
       'Other|Back-end Developer|Front-end Developer|One-person shop',
       'Other|One-person shop|Back-end Developer|Sales|Support|DevOps/SysAdmin|Dev Evangelist/Advocate|Supervisor/Team Lead',
       'Back-end Developer|One-person shop',
       'One-person shop|Designer|Front-end Developer|Back-end Developer|Support',
       'Designer|Front-end Developer|Back-end Developer|DevOps/SysAdmin',
       'One-person shop|Front-end Developer|Back-end Developer|Sales|Support|DevOps/SysAdmin',
       'DevOps/SysAdmin|Back-end Developer|One-person shop',
       'Other|Back-end Developer',
       'DevOps/SysAdmin|Support|Sales|One-person shop|Designer|Front-end Developer|Back-end Developer',
       'Designer|Front-end Developer|Back-end Developer|Supervisor/Team Lead',
       'Front-end Developer|Back-end Developer|Support|Dev Evangelist/Advocate',
       'Executive Leadership|Supervisor/Team Lead|HR|DevOps/SysAdmin|Support|Sales|Back-end Developer|One-person shop|Designer|Front-end Developer',
       'Front-end Developer|Back-end Developer|Support|DevOps/SysAdmin|Dev Evangelist/Advocate',
       'Supervisor/Team Lead|Executive Leadership',
       'One-person shop|Front-end Developer',
       'Other|Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|One-person shop',
       'Support|DevOps/SysAdmin',
       'One-person shop|Front-end Developer|Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead',
       'Dev Evangelist/Advocate|DevOps/SysAdmin|Back-end Developer',
       'Dev Evangelist/Advocate|Support|Back-end Developer|Front-end Developer',
       'One-person shop|Back-end Developer|Sales|Support|Supervisor/Team Lead|Executive Leadership',
       'DevOps/SysAdmin|Support|Back-end Developer',
       'Designer|Front-end Developer|Back-end Developer|Support|DevOps/SysAdmin|Supervisor/Team Lead',
       'Other|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer',
       'Executive Leadership|Supervisor/Team Lead|Sales',
       'Other|Front-end Developer|Designer',
       'One-person shop|Designer|Front-end Developer|Supervisor/Team Lead',
       'Designer|Front-end Developer',
       'Designer|Front-end Developer|Back-end Developer|DevOps/SysAdmin|Other',
       'Other|Dev Evangelist/Advocate|Back-end Developer|Front-end Developer',
       'DevOps/SysAdmin|Other',
       'Other|Executive Leadership|Supervisor/Team Lead|HR|Support|Sales|Designer|One-person shop',
       'Back-end Developer|Support|DevOps/SysAdmin',
       'Supervisor/Team Lead|Designer|Front-end Developer|Support',
       'Executive Leadership|One-person shop|Front-end Developer|Back-end Developer|Support|Supervisor/Team Lead',
       'Executive Leadership|Supervisor/Team Lead|Designer',
       'Support|Front-end Developer|Designer',
       'Other|Support|Back-end Developer|Front-end Developer|Designer',
       'One-person shop|Designer|Front-end Developer|Back-end Developer',
       'Dev Evangelist/Advocate|DevOps/SysAdmin|Designer|Front-end Developer|Support',
       'Other|Designer|Front-end Developer', 'Other|Front-end Developer',
       'Front-end Developer|One-person shop',
       'Designer|Front-end Developer|Back-end Developer|Sales|Supervisor/Team Lead',
       'Front-end Developer|Back-end Developer|Dev Evangelist/Advocate',
       'Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Support',
       'Front-end Developer|Back-end Developer|Support|Supervisor/Team Lead',
       'Supervisor/Team Lead|Front-end Developer|Back-end Developer|Dev Evangelist/Advocate',
       'Supervisor/Team Lead|DevOps/SysAdmin|Front-end Developer|Back-end Developer',
       'DevOps/SysAdmin|Back-end Developer|Front-end Developer|One-person shop',
       'One-person shop|Designer',
       'DevOps/SysAdmin|Support|Back-end Developer|One-person shop',
       'Dev Evangelist/Advocate|Front-end Developer|Back-end Developer|DevOps/SysAdmin',
       'DevOps/SysAdmin|Support|One-person shop',
       'Designer|Support|Supervisor/Team Lead',
       'Other|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|Designer|One-person shop',
       'Support|Designer', 'One-person shop|Other',
       'Executive Leadership|Supervisor/Team Lead|Front-end Developer|Back-end Developer',
       'Designer|Front-end Developer|Back-end Developer|Executive Leadership|Other',
       'Designer|Front-end Developer|Back-end Developer|Supervisor/Team Lead|Executive Leadership',
       'Supervisor/Team Lead|DevOps/SysAdmin|Support|Front-end Developer|Designer|One-person shop',
       'Front-end Developer|Back-end Developer|DevOps/SysAdmin|Dev Evangelist/Advocate',
       'Executive Leadership|Supervisor/Team Lead|Back-end Developer|DevOps/SysAdmin',
       'Support|Front-end Developer|Back-end Developer',
       'Front-end Developer|Back-end Developer|Sales|Support|DevOps/SysAdmin|Supervisor/Team Lead|Executive Leadership',
       'One-person shop|Front-end Developer|Back-end Developer|Support|Other',
       'One-person shop|Designer|Front-end Developer|Back-end Developer|Sales|Support',
       'Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer|Designer|Front-end Developer',
       'Supervisor/Team Lead|Sales',
       'Other|DevOps/SysAdmin|Support|Back-end Developer',
       'Supervisor/Team Lead|Back-end Developer|Support|DevOps/SysAdmin',
       'Dev Evangelist/Advocate|One-person shop|Back-end Developer|Support|DevOps/SysAdmin',
       'Other|One-person shop', 'Executive Leadership|Other',
       'One-person shop|Designer|Front-end Developer|Back-end Developer|Support|DevOps/SysAdmin|Other',
       'Other|Dev Evangelist/Advocate|Support',
       'Support|Designer|Front-end Developer', 'Designer|One-person shop',
       'Designer|Supervisor/Team Lead', 'Front-end Developer|Support',
       'Executive Leadership|Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Front-end Developer|One-person shop',
       'One-person shop|Designer|Front-end Developer',
       'Executive Leadership|Supervisor/Team Lead|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer',
       'Front-end Developer|Back-end Developer|Supervisor/Team Lead|Executive Leadership',
       'Executive Leadership|Supervisor/Team Lead|Back-end Developer|Front-end Developer|Designer',
       'Other|DevOps/SysAdmin|Back-end Developer',
       'Other|Back-end Developer|Supervisor/Team Lead',
       'Front-end Developer|Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead|Executive Leadership',
       'Sales|Support|DevOps/SysAdmin|Executive Leadership',
       'Executive Leadership|Back-end Developer|Front-end Developer',
       'DevOps/SysAdmin|Support|Front-end Developer|Back-end Developer',
       'One-person shop|Back-end Developer|Dev Evangelist/Advocate',
       'Supervisor/Team Lead|Dev Evangelist/Advocate|Back-end Developer|Designer|Front-end Developer',
       'Supervisor/Team Lead|Support|Front-end Developer|Back-end Developer',
       'Front-end Developer|Executive Leadership',
       'Other|Dev Evangelist/Advocate',
       'Back-end Developer|Supervisor/Team Lead|Other',
       'Front-end Developer|Back-end Developer|Dev Evangelist/Advocate|Supervisor/Team Lead',
       'Front-end Developer|Back-end Developer|Support|DevOps/SysAdmin|Executive Leadership',
       'Other|Supervisor/Team Lead|Front-end Developer',
       'Other|Supervisor/Team Lead', 'DevOps/SysAdmin|Designer',
       'Supervisor/Team Lead|DevOps/SysAdmin|HR',
       'DevOps/SysAdmin|Designer|Front-end Developer|Back-end Developer',
       'Front-end Developer|Back-end Developer|Other',
       'Support|Sales|Designer',
       'Front-end Developer|Back-end Developer|Support|Other',
       'Executive Leadership|Supervisor/Team Lead|Support|Sales|Designer|Front-end Developer|Back-end Developer',
       'Other|Supervisor/Team Lead|DevOps/SysAdmin|Back-end Developer|Support',
       'Other|Front-end Developer|Designer|One-person shop',
       'Front-end Developer|Designer|One-person shop',
       'DevOps/SysAdmin|Support|Sales|Front-end Developer|Designer|One-person shop',
       'Supervisor/Team Lead|Front-end Developer|Back-end Developer|Support|DevOps/SysAdmin',
       'Other|Supervisor/Team Lead|Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|One-person shop',
       'Other|One-person shop|Designer|Front-end Developer|Back-end Developer|Support|Supervisor/Team Lead',
       'Supervisor/Team Lead|Support|Back-end Developer|Front-end Developer',
       'Other|Supervisor/Team Lead|DevOps/SysAdmin|Support|Front-end Developer|Back-end Developer',
       'Back-end Developer|Support|Supervisor/Team Lead',
       'Supervisor/Team Lead|Designer',
       'Support|Back-end Developer|Front-end Developer|One-person shop',
       'Other|One-person shop|Designer|Front-end Developer',
       'One-person shop|Designer|Sales|Support|Supervisor/Team Lead',
       'DevOps/SysAdmin|Support|Back-end Developer|One-person shop|Front-end Developer',
       'Support|Sales|Back-end Developer|Front-end Developer|Designer|One-person shop',
       'Dev Evangelist/Advocate|DevOps/SysAdmin|Designer|Front-end Developer|Back-end Developer',
       'Supervisor/Team Lead|Front-end Developer|Designer',
       'Executive Leadership|Supervisor/Team Lead|Dev Evangelist/Advocate|Back-end Developer',
       'One-person shop|Designer|Sales|Executive Leadership',
       'Support|Back-end Developer|Front-end Developer|Designer',
       'Supervisor/Team Lead|Support|One-person shop|Designer|Front-end Developer|Sales',
       'One-person shop|Designer|Support',
       'Dev Evangelist/Advocate|DevOps/SysAdmin|Support|Back-end Developer|Front-end Developer|One-person shop',
       'One-person shop|Designer|Front-end Developer|Support|Dev Evangelist/Advocate',
       'Designer|Front-end Developer|Back-end Developer|Other',
       'Executive Leadership|Supervisor/Team Lead|Front-end Developer',
       'One-person shop|DevOps/SysAdmin',
       'One-person shop|Front-end Developer|Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead|Executive Leadership',
       'One-person shop|Designer|Front-end Developer|Back-end Developer|Dev Evangelist/Advocate|Supervisor/Team Lead',
       'Other|Supervisor/Team Lead|Dev Evangelist/Advocate',
       'Supervisor/Team Lead|Back-end Developer|Designer',
       'Back-end Developer|DevOps/SysAdmin|Supervisor/Team Lead|Executive Leadership',
       'Supervisor/Team Lead|Front-end Developer|Back-end Developer|DevOps/SysAdmin|Dev Evangelist/Advocate'],
      dtype=object)

In [14]:
df["If yes, what condition(s) have you been diagnosed with?"].unique()

array([nan,
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Stress Response Syndromes|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Substance Use Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Obsessive-Compulsive Disorder',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Attention Deficit Hyperactivity Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder|Addictive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Obsessive-Compulsive Disorder',
       'Attention Deficit Hyperactivity Disorder|Pervasive Developmental Disorder (Not Otherwise Specified)',
       'Seasonal Affective Disorder', 'Burn out', 'PDD-NOS',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Attention Deficit Hyperactivity Disorder',
       'Post-traumatic Stress Disorder|Dissociative Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder|Stress Response Syndromes|Dissociative Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder|Substance Use Disorder|Addictive Disorder',
       'Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder',
       'Depression', "Autism (Asperger's)",
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Traumatic Brain Injury',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Dissociative Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Addictive Disorder',
       'Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Stress Response Syndromes|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Gender Dysphoria',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Asperges',
       'Obsessive-Compulsive Disorder',
       'Attention Deficit Hyperactivity Disorder|PTSD (undiagnosed)',
       'Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Stress Response Syndromes',
       'Psychotic Disorder (Schizophrenia, Schizoaffective, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder|Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Stress Response Syndromes',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes|Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Addictive Disorder|Autism',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Obsessive-Compulsive Disorder|Substance Use Disorder',
       'Substance Use Disorder', 'Stress Response Syndromes',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes|Addictive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Dissociative Disorder',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Addictive Disorder',
       'Sexual addiction',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Addictive Disorder',
       'Combination of physical impairment (strongly near-sighted) with a possibly mental one (MCD / "ADHD", though its actually a stimulus filtering impairment)',
       'Substance Use Disorder|Addictive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Substance Use Disorder|Addictive Disorder',
       'Attention Deficit Hyperactivity Disorder|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Stress Response Syndromes|Sleeping Disorder',
       "I haven't been formally diagnosed, so I felt uncomfortable answering, but Social Anxiety and Depression.",
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Post-traumatic Stress Disorder',
       'Eating Disorder (Anorexia, Bulimia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Obsessive-Compulsive Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder',
       'Autism Spectrum Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder|Dissociative Disorder|Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder|Stress Response Syndromes|Addictive Disorder',
       'Transgender|Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Dissociative Disorder|Autism',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Stress Response Syndromes',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Addictive Disorder|Intimate Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Dissociative Disorder|Autism',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes',
       'Attention Deficit Hyperactivity Disorder|Addictive Disorder',
       'Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Obsessive-Compulsive Disorder|ADD (w/o Hyperactivity)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Stress Response Syndromes|Dissociative Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Addictive Disorder',
       'Eating Disorder (Anorexia, Bulimia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Dissociative Disorder',
       'Schizotypal Personality Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes|Autism spectrum disorder',
       'Obsessive-Compulsive Disorder|Eating Disorder (Anorexia, Bulimia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)'],
      dtype=object)

In [15]:
df["Do you currently have a mental health disorder?"].unique()

array(['No', 'Yes', 'Maybe'], dtype=object)

In [16]:
df["What country do you live in?"].unique()

array(['United Kingdom', 'United States of America', 'Canada', 'Germany',
       'Netherlands', 'Czech Republic', 'Lithuania', 'Australia',
       'France', 'Venezuela', 'Poland', 'Belgium', 'Brazil', 'Denmark',
       'Sweden', 'Russia', 'Spain', 'India', 'Mexico', 'Switzerland',
       'Norway', 'Argentina', 'Ireland', 'Italy', 'Finland', 'Colombia',
       'Costa Rica', 'Vietnam', 'Bulgaria', 'New Zealand', 'South Africa',
       'Slovakia', 'Austria', 'Bangladesh', 'Algeria', 'Pakistan',
       'Afghanistan', 'Greece', 'Romania', 'Other', 'Brunei', 'Japan',
       'Iran', 'Hungary', 'Israel', 'Ecuador', 'Bosnia and Herzegovina',
       'China', 'Chile', 'Guatemala', 'Taiwan', 'Serbia', 'Estonia'],
      dtype=object)

In [17]:
df['If maybe, what condition(s) do you believe you have?'].unique()

array([nan, 'Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Psychotic Disorder (Schizophrenia, Schizoaffective, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Obsessive-Compulsive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Stress Response Syndromes',
       'Attention Deficit Hyperactivity Disorder|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)',
       'Obsessive-Compulsive Disorder|Suicidal Ideation',
       'Attention Deficit Hyperactivity Disorder',
       "We're all hurt, right?!",
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder|Stress Response Syndromes',
       'Burnout',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Addictive Disorder',
       'Gender Identity Disorder', 'Substance Use Disorder',
       'Stress Response Syndromes|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder|Stress Response Syndromes|Addictive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Tinnitus',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder',
       'Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Addictive Disorder|Substance Use Disorder|Obsessive-Compulsive Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Stress Response Syndromes|Addictive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Stress Response Syndromes',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Stress Response Syndromes',
       'Stress Response Syndromes|Substance Use Disorder|Addictive Disorder',
       'Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder|Dissociative Disorder|Depersonalisation',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Psychotic Disorder (Schizophrenia, Schizoaffective, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'post-partum / anxiety',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Obsessive-Compulsive Disorder|Stress Response Syndromes',
       'Dissociative Disorder|Post-traumatic Stress Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Stress Response Syndromes',
       'Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Dissociative Disorder',
       'Dissociative Disorder|Stress Response Syndromes|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Dissociative Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Substance Use Disorder|Addictive Disorder',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Addictive Disorder',
       'Attention Deficit Hyperactivity Disorder|Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Eating Disorder (Anorexia, Bulimia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Dissociative Disorder|Substance Use Disorder',
       'Obsessive-Compulsive Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Addictive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Addictive Disorder',
       'Asperger Syndrome',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes|Addictive Disorder',
       "Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Asperger's",
       'Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder',
       'depersonalization disorder',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Autism',
       'Obsessive-Compulsive Disorder|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Addictive Disorder',
       'Stress Response Syndromes|Post-traumatic Stress Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Attention Deficit Hyperactivity Disorder|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Substance Use Disorder|Obsessive-Compulsive Disorder',
       'Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Addictive Disorder'],
      dtype=object)

In [18]:
df["If so, what condition(s) were you diagnosed with?"].unique()

array(['Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)',
       nan,
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Substance Use Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Obsessive-Compulsive Disorder',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Obsessive-Compulsive Disorder',
       'Attention Deficit Hyperactivity Disorder|PDD-NOS (see above)',
       'Seasonal Affective Disorder', 'Burn out',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder',
       'PDD-NOS',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Suicidal Ideation',
       'Attention Deficit Hyperactivity Disorder',
       'Post-traumatic Stress Disorder|Dissociative Disorder',
       'Depression',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Stress Response Syndromes',
       'Gender Identity Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Obsessive-Compulsive Disorder',
       'Addictive Disorder|Substance Use Disorder|Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder',
       'Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Stress Response Syndromes',
       'Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Dissociative Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Stress Response Syndromes',
       "Autism (Asperger's)",
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Dissociative Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Gender Dysphoria',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Obsessive-Compulsive Disorder', 'Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Eating Disorder (Anorexia, Bulimia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder',
       'Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Stress Response Syndromes|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Psychotic Disorder (Schizophrenia, Schizoaffective, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Substance Use Disorder|Addictive Disorder',
       'Substance Use Disorder|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes|Substance Use Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Addictive Disorder|Autism',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Addictive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Post-traumatic Stress Disorder|Stress Response Syndromes',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Autism - while not a "mental illness", still greatly affects how I handle anxiety',
       'Obsessive-Compulsive Disorder|Substance Use Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Disorder',
       'Post-traumatic Stress Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Substance Use Disorder|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Addictive Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Attention Deficit Hyperactivity Disorder|MCD (when it was diagnosed, the ultra-mega "disorder" ADHD didn\'t exist yet)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Dissociative Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Eating Disorder (Anorexia, Bulimia, etc)|posttraumatic stress disourder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Addictive Disorder',
       'attention deficit disorder (but not the hyperactive version)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Attention Deficit Hyperactivity Disorder|Mood Disorder (Depression, Bipolar Disorder, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Aspergers',
       'Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Dissociative Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Substance Use Disorder|Addictive Disorder',
       'Stress Response Syndromes|Mood Disorder (Depression, Bipolar Disorder, etc)|Anxiety Disorder (Generalized, Social, Phobia, etc)',
       'Autism Spectrum Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Obsessive-Compulsive Disorder|Addictive Disorder',
       'Asperger Syndrome',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Dissociative Disorder|Autism',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Dissociative Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Intimate Disorder',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)',
       'Mood Disorder (Depression, Bipolar Disorder, etc)|Psychotic Disorder (Schizophrenia, Schizoaffective, etc)|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Post-traumatic Stress Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Post-traumatic Stress Disorder|Substance Use Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder',
       'Anxiety Disorder (Generalized, Social, Phobia, etc)|Personality Disorder (Borderline, Antisocial, Paranoid, etc)|Dissociative Disorder',
       'ADD (w/o Hyperactivity)',
       'Addictive Disorder|Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Eating Disorder (Anorexia, Bulimia, etc)|Attention Deficit Hyperactivity Disorder|Obsessive-Compulsive Disorder|Post-traumatic Stress Disorder|Dissociative Disorder',
       'Eating Disorder (Anorexia, Bulimia, etc)',
       'Schizotypal Personality Disorder', 'autism spectrum disorder'],
      dtype=object)